### ISSUE TITLE
Newly introduced build problems?

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#103]
This cannot be compiled:

```
#include "qpp.h"
int main()
{
    return 0;
}
```

This is fine:

```
#include <iostream>
#include "qpp.h"
int main()
{
    return 0;
}
```
So, the `qpp.h` is not self-contained because of the external dependency on `iostream`.

Not sure if that was recently introduced or not.

**Comment by vsoftco** [comment]
Good point, thanks. This issue is in the code for quite a long time, as we write (`std::cerr`) some additional context information before throwing exceptions. It is indeed a good idea of not having `<iostream>` a standard dependency, I will try to refactor the code.

**Comment by DevelopDaily** [comment]
Having a dependency on the `<iostream>` does not bother me at all as long as it does not come as a surprise.  I think the fix could be just to add this to the `qpp.h`

`#include <iostream>`


After all, the `qpp.h` has already included a whole bunch of `std `libraries, including this:

`#include <ostream>`

It seems the `<iostream> `has been forgotten to be added into the master header `qpp.h`. I guess, it is kind of a typo.

**Comment by vsoftco** [comment]
I think I'll get rid of explicit <iostream> dependency. It's quite a large header, and it's not really necessary, so I want to leave the user the opportunity to use e.g. `<cstdio>` if s/he wants. I personally don't like heaving an I/O header as part of a header-only library.

**Comment by DevelopDaily** [comment]
Cool. Whenever possible, less dependency is always better, of course.

**Comment by vsoftco** [comment]
Fixed on my side

**Comment by DevelopDaily** [comment]
Great. Thanks.
