### ISSUE TITLE
Install target is missing

### ISSUE THREAD

**Issue by yurivict** [softwareQinc/qpp#105]
Header-only libraries should install headers into ```include/```.

Also it's best to install many headers into a dedicated directory under ```include/```, for example ```include/qpp```.

**Comment by vsoftco** [comment]
@yurivict It should. When I do 

`cmake .. && sudo make install` 

I end up with the library installed in `/usr/local/include/qpp`.

**Comment by yurivict** [comment]
It was added after the last release.

Thanks!
