### ISSUE TITLE
Bug Report: Semantic Error 

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#107]
I am not sure if this should be filed against `qpp` or `staq`. Anyway, here is a simple test case.

```
OPENQASM 2.0;
include "qelib1.inc";

qreg h[1];
qreg q[1];
h q[0];
```

That cannot be run by `qpp` because the `h` is declared as a gate and a register. The trouble is that the script can be parsed by the `staq `perfectly.

I think they should succeed or fail consistently.

**Comment by vsoftco** [comment]
Thanks! We'll investigate. Currently the parser in staq and qpp are not identical. We should probably converge to a single point of entry. Adding @meamy to the thread.

**Comment by vsoftco** [comment]
@DevelopDaily Fixing in progress... we decoupled the parser from both qpp and staq, and use only one version. Will release a fresh new staq and qpp version soon.

**Comment by vsoftco** [comment]
both staq and qpp now use the same parser
