### ISSUE TITLE
ParseError on <id>

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#108]
Here is a test case:

```
OPENQASM 2.0;
include "qelib1.inc";

gate Aa a
{
    x a;
}

qreg q[1];

```
That will fail because of the name `Aa`. 

According to the Open QASM spec, the regular expression of the `<id>` is `[a-z][A-Za-z0-9_]*`

The `Aa` is a match, isn't it?

**Comment by vsoftco** [comment]
@DevelopDaily Aa shouldn't match, right? Look at https://regexr.com/ with `[a-z][A-Za-z0-9_]*` as the regex. The regex starts with `[a-z]` which must match single chars. Adding @meamy just to confirm, my regex skills are quite limited :)

**Comment by meamy** [comment]
Yes, according to the spec ```Aa``` isn't a valid gate identifier. My guess is it's to make code look more uniform, rather than for any technical reason.

**Comment by DevelopDaily** [comment]
You are correct.

Sorry. I punched the expression into [https://regex101.com/](https://regex101.com/) and misinterpreted its results.

Thanks.

**Comment by meamy** [comment]
No worries at all! We're very glad to have you checking these things!
