### ISSUE TITLE
Phase shift computation/removal

### ISSUE THREAD

**Issue by antoine-bussy** [softwareQinc/qpp#111]
Hi,

I'm running the following test:
```c++
    auto state = qpp::randket().eval();
    auto const [result, probabilities, resulting_state] = qpp::measure(state, qpp::gt.H);
    EXPECT_MATRIX_CLOSE(resulting_state[0], qpp::st.plus(), 1e-12);
    EXPECT_MATRIX_CLOSE(resulting_state[1], qpp::st.minus(), 1e-12);
```
The tests fail because the resulting states have a phase shift. Is there a mean to remove or compute the phase shift already in the API? Or to compare two states up to a phase shift?

**Comment by vsoftco** [comment]
@antoine-bussy That's a good point. In the API, we basically translate the measurement to Kraus operators, so the resulting state is effectively K_i|psi>. In this case, it'll be |+><+|psi>, so indeed you get a phase. This I agree is a bit counter-intuitive for basis measurements, but it is consistent with the literature, e.g. [Nielsen and Chuang Sec. 2.2.3, "Quantum Measurements"]. So for now I'm tempted to leave it as is. Most of the time in QM one doesn't talk about the "resulting" state, and if one does, then usually says the resulting state belongs to the "ray" in the Hilbert space P*H (where P is the projector onto the basis state, and P*H denotes the subspace of H onto which P projects). I.e., P*H:={P|psi> | |psi>\in H}.

To get rid of the global phase, simply divide the resulting state by one of its coefficients, e.g., `resulting_state[0]/resulting_state[0][0]`.

In general, if you have `|psi0>` and `|psi1>=e^{i\phi}|psi>`, then you compute the phase as `psi1[0]/psi0[0]`, so `psi1 * psi0[0]/psi1[0]` will give you back `|psi0>`. Hope this helps.

**Comment by vsoftco** [comment]
Also, the simplest way to compare two states up to a phase shift is to simply compare the projectors onto them, i.e. `prj(resulting_state[0])` and `prj(resulting_state[1])` with `prj(st.plus())` and `prj(st.minus()`, respectively. The projectors will absorb the global phases.

**Comment by vsoftco** [comment]
@antoine-bussy That's a nice test. I may implement such a "collinear" function in q++.

**Comment by antoine-bussy** [comment]
Not so nice... I wasn't satisfied with it because it doesn't generalize well to upper dimensions, so I switched to a Cauchy-Schwarz-based test:
```c++
template < Matrix Actual, Matrix Expected, RealNumber Precision >
auto collinear(Actual const& actual, Expected const& expected, Precision const& precision)
{
    auto const n2 = actual.squaredNorm() * expected.squaredNorm();
    return n2 - std::norm(actual.dot(expected)) < precision * n2;
}
```

**Comment by vsoftco** [comment]
@antoine-bussy Indeed, I was just thinking about that...
