### ISSUE TITLE
Kronecker product operator

### ISSUE THREAD

**Issue by antoine-bussy** [softwareQinc/qpp#112]
I'm starting to use the kronecker product a lot (for kets only), and I'm thinking that using an operator may be very convenient.
Maybe the ```|``` operator?
Same question goes for the direct sum.

What do you think?

**Comment by vsoftco** [comment]
This is a good point. I'm just hesitant about the symbol `|` for tensor products, although I cannot come up with anything better. What would you propose for direct sum?

**Comment by antoine-bussy** [comment]
I implemented it and tried to use it, and it was actually not fun at all to use! Because of operator precedence, I had to think hard about parenthesis... So it's not an improvement in usability nor in readability.

**Comment by vsoftco** [comment]
Yeah, the precedence is lower than `+`, so it'll create a lot of issues... closing it.
