### ISSUE TITLE
Mismatch issues of the crz

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#118]
These issues may be related to both `qpp `#117 and the `staq `https://github.com/softwareQinc/staq/issues/43, which fixed the state distortion problem by `crz` and may have introduced some new issues(?)

Here is a test script:

```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];

x q;
crz(1) q[0], q[1];
```

Qiskit produces the final state:

`[ 0+0j, 0+0j, 0+0j, 0.878+0.479j ]`

`qpp`:

`0  0  0  0.540302 + 0.841471i`

The `crz `is not documented in https://github.com/softwareQinc/qpp/blob/main/DISCREPANCIES.md.

**Comment by 525125** [comment]
Continuing from https://github.com/softwareQinc/qpp/issues/117#issuecomment-997959585:

Since `rz` and `u1` are identical, it only makes sense for `crz` and `cu1` to be identical as well (and they were made the same when fixing `crz`). This ensures that `CRZ = CTRL-diag(RZ)`.

**Comment by DevelopDaily** [comment]
Mimicking the tests in the issue #117, I did four tests to show the final states out of `crz `and `cu1 `on QISKIT and qpp.

In QISKIT:

```
x q;
crz(pi/3) q[0], q[1];
// => [ 0+0j, 0+0j, 0+0j, 0.866+0.5j ]
```

```
x q;
cu1(pi/3) q[0], q[1];
// => [ 0+0j, 0+0j, 0+0j, 0.5+0.866j ]
```

In qpp:

```
x q;
crz(pi/3) q[0], q[1];
// => 0  0  0  0.5 + 0.866025i
```

```
x q;
cu1(pi/3) q[0], q[1];
// => 0  0  0  0.5 + 0.866025i
```

The same problem, as expected, exists.

**Comment by vsoftco** [comment]
@DevelopDaily can you check this now please?

**Comment by DevelopDaily** [comment]
Passed the simple test cases. Will test more complex cases in the #117
