### ISSUE TITLE
QCircuit.get_nc() returns a wrong value

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#120]
The test program:

```
#include <iostream>
#include "qpp.h"

int main(int argc, char** argv) {
    using namespace qpp;

    QCircuit qc = qasm::read(std::cin);
    QEngine q_engine{qc};
    q_engine.execute();
    std::cout<<qc.get_nc()<<std::endl;
}
```

The input file:

```
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];
creg c[1];
```

We should expect the printout to be `1`, shouldn't we? In reality, it is `2`.

I have got a hunch: if this problem had not existed, I wouldn't have opened the issue #119. This one may be the root cause of the problems in `QEngine.get_stats(), QEngine.to_JSON()`, etc.

Please note `QCircuit.get_nq()` is wrong too.

**Comment by vsoftco** [comment]
I can confirm. For some reason, the QCircuit constructed when reading a qasm file sets nc=nq=maximum(classical_regs, quantum_regs). Adding @meamy to this as well.

**Comment by meamy** [comment]
Looks like the number of bits and qubits are being supplied to the `QCircuit` constructor in the wrong order [here](https://github.com/softwareQinc/qpp/blob/main/include/qasm/qasm.hpp#L817) and [here](https://github.com/softwareQinc/qpp/blob/main/include/qasm/qasm.hpp#L833). `bits` and `qubits` just need to be switched around and everything works.

@vsoftco Let me know if you want me to make a pull req, or to just swap them yourself. Looks like I don't have push permission.

**Comment by vsoftco** [comment]
@meamy I just realized that as well, and pushed it, super tiny typo :)
