### ISSUE TITLE
Regarding cmat U = gt.CNOT * kron(gt.H, gt.Id2);

### ISSUE THREAD

**Issue by Penghmed** [softwareQinc/qpp#125]
is * the tensor product operator? So what is the Kron operator?

**Comment by vsoftco** [comment]
`*` is the usual multiplication operator. `kron` is the tensor product.

**Comment by Penghmed** [comment]
I try make this in C++:

$\operatorname{CNOT}(H \otimes I)\left\|\psi_{1}\right\rangle\left\|\psi_{2}\right\rangle$

Appear here:https://quantumcomputing.stackexchange.com/questions/24181/epr-pairs-bell-states-preparation-circuit-in-sympy 

Can make help?

**Comment by vsoftco** [comment]
`gt.CNOT*kron(gt.H, gt.Id2)*kron(psi1, psi2)`

**Comment by Penghmed** [comment]
How know when use multiply, and when use Kron? 
Thanks you
