### ISSUE TITLE
How can calculate inner/outer product?

### ISSUE THREAD

**Issue by Penghmed** [softwareQinc/qpp#126]
I am interested: Φ1=(|00> − i|11>), Φ2=(|01> −|11>) and calculate <Φ1|Φ2> and |Φ1>|Φ2>

**Comment by vsoftco** [comment]
`ip(phi1,phi2` and `kron(phi1,phi2)`

**Comment by Penghmed** [comment]
Thanks you very help. 
And <Φ1| A |Φ2> also <Φ1| A |Φ2>*  ?
