### ISSUE TITLE
Hardy’s paradox

### ISSUE THREAD

**Issue by BoltzmannEntropy** [softwareQinc/qpp#133]
Dear qpp team,
I'd like to use qpp for the experimental verification of Hardy's paradox in a brief paper I'm writing. Are there any reasons why I should not utilise qpp? For instance, is there a reason to suppose that implementing portions of the paradox would be impossible?
This is a reference implementation:
https://github.com/maria-violaris/quantum-paradoxes/blob/main/A%20quantum%20lie%20detector%20for%20Hardy's%20paradox.ipynb

All the best,

**Comment by vsoftco** [comment]
@BoltzmannEntropy No reason why it wouldn't work, qpp is a universal simulator.

**Comment by BoltzmannEntropy** [comment]
Great thanks, sounds good. I can send you a summary of the paper if you share your email.
