### ISSUE TITLE
Control on another quantum circuit

### ISSUE THREAD

**Issue by francler1** [softwareQinc/qpp#165]
I was wondering if it is possible to create a control between one/more qubits and another quantum circuit. I am looking for something like this
 
```
qpp:QCircuit qc1(3);
 
// add some gates to qc1 OR even prepare a state for q1

qpp::QCircuit qc2(3);
qc2.compose( qc1 /*target*/, {0,1,2} /* control */ );
```

I hope this is understandable. In case, the same thing I am looking for can be obtained in Qiskit with:
 
```
qreg = QuantumRegister(3)
 
QuantumCircuit qc1(3)

# add some gates or prepare state in qc1

QuantumCircuit qc2(qreg)
qc2.compose(qc1.control(1), qreg[::], inplace=True)
```

**Comment by vsoftco** [comment]
@francler1  Thank you for the suggestion. Currently this function is not (yet) implemented. We are working on implementing it, and will close this issue when ready.

**Comment by vsoftco** [comment]
Done #167
