### ISSUE TITLE
Manage external dependencies on googletest using a submodule

### ISSUE THREAD

**Issue by M1TE5H** [softwareQinc/qpp#168]
In order to ensure that the [`googletest`](https://github.com/google/googletest) source continues to receive the latest commits from upstream, it could be worth embedding the subproject repository as a submodule i.e. rather than including the static code (and the associated bulk/debt) from a previous release.

If the submodule suggestion seems sensible, then here is a list of the (relatively) minor changes:

0. _Optional._ Remove the entire `unit_tests\libs\googletest-release-1.12.1` folder to clean up navigation of the `qpp` project repository.
1.  Add the `googletest` project from Google’s GitHub account as a submodule: `git add submodule https://www.github.com/google/googletest <PATH>/<TO>/googletest`. 
2. Update `unit_tests\CMakeLists.txt` accordingly and perhaps provide optional fetching if `googletest` is missing.
3. Update the GitHub actions and Docker instructions to accommodate a `--recursive` submodule clone.
4. Update relevant instructions in the `README.md` to explain the need for a  `--recursive` submodule update (or just provide an end user-facing script to automate the updating).

And if possible, feel free to assign this issue to me.

**Comment by vsoftco** [comment]
@M1TE5H Thanks for the suggestion. We'll look into it. Meanwhile keeping this open.

**Comment by vsoftco** [comment]
@M1TE5H Fixed by #169 All dependencies, i.e., Eigen3, pybind11, and GoogleTest, are now pulled via CMake's FetchContent (in case they're not detected by CMake). We prefer this approach instead of submodules, as it is more flexible (also, users may forget to `git clone --recurse-submodules`)
