### ISSUE TITLE
'P' and 'SX' gate support

### ISSUE THREAD

**Issue by zhongMou-lilSister** [softwareQinc/qpp#172]
Hi,

I am importing qasm circuit files. There exists P and SX gates in certain circuits. It seems that qpp does not support these gates yet. Could you please add a patch to support these gates? Thank you and I really appreciate it!

**Comment by vsoftco** [comment]
@zhongMou-lilSister Assuming you're referring to `P(\lambda)` and `SX` from OpenQASM, you can implement them as follows.`SX=e^(i*\pi/4) RX(pi/2)`. `P(\lambda)=e^(i*\lambda/2)RZ(\lambda)`. See https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.SXGate and https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.PhaseGate. `RX` and `RZ` are implemented in `qpp`. We decided to stick with the "standard" gates from Nielsen and Chuang, as all other gates can be easily implemented in terms of those.

**Comment by zhongMou-lilSister** [comment]
Thank you for your comment!
