### ISSUE TITLE
A little inconsistency of the gate RZ

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#70]
The current implementation of the gate RZ is simply to call `Rn(theta, {0, 0, 1})`. That is good. The current definition of the rz in the QASM is `gate rz(phi) a { u1(phi) a; }`. They will end up with two different matrices. Both are correct, but they just look different. Let me illustrate them in this image:

![RZ](https://user-images.githubusercontent.com/54299975/71784297-1f164180-2fc0-11ea-9dec-c0f49b724936.png)

The `Rn(theta, {0, 0, 1})` will be in the form of "A"; `gate rz(phi) a { u1(phi) a; }` "B".

Since the latter looks prettier, would it be nice to shift the phase by θ/2, as suggested in the image, before the `cmat RZ(double theta) const` returns?

How do you think?

**Comment by vsoftco** [comment]
Thanks! The only issue is that a phase becomes important in a controlled-operation. Say that the matrix is `Id_phi := e^{i \phi} x Identity`. Then this unitary produces the same effect as `Identity` if acting on one qubit. But, if we construct something like `CTRL-Id_phi`, then the effects are visible, e.g. acting this gate on `|00>+|11>` will produce `|00> + e^{i\phi}|11>`, which is not just a phase times the initial state. In our case, we need to be consistent. 

Currently the qasm `rz` returns `gt.RZ`, see https://github.com/softwareQinc/qpp/blob/0aced6984157c2874f7fcdd263f2c11e9b994200/include/qasm/ast.h#L73

But if one uses qiskit, one would expect (as you mention), to have `rz` return `diag(1, phase)`. I am tempted to just make `rz` return `diag(1, phase)` (which will be different from `gt.RZ`, so we implement the qiskit spec correctly.

**Comment by vsoftco** [comment]
So I ended up implementing `rz` as the QISKIT specs, i.e. `diag(1, e^{i\phi})`, and kept `gt.RZ` as is  in qpp; also documented in `ast.h` why the choice.

**Comment by DevelopDaily** [comment]
Great. A well-thought-out solution. Thanks.

The rx and ry are consistent.
