### ISSUE TITLE
qpp hangs when it runs this qasm file.

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#71]
The staq [issue](https://github.com/softwareQinc/staq/issues/9) has been fixed.

It turns out that the qpp has a similar issue. If you use the QEngine to execute this simple file, i.e., a file with a comment line without a newline/linefeed at the end, the engine will hang.

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg a[1];
> //

**Comment by vsoftco** [comment]
@DevelopDaily thanks! Q++ has code from staq, I'll modify it accordingly.

**Comment by vsoftco** [comment]
Fixed

**Comment by vsoftco** [comment]
@DevelopDaily Done
