### ISSUE TITLE
Why not SEARCHENGINE = YES

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#74]
Would you please consider setting that to YES in the Doxyfile?

I think the search engine costs very little, but offers a lot of convenience. After all, the `staq `project sets that to YES by default.

Otherwise, the `git `would have to deal with that whenever I pull the master, after I make a local change to YES.

Thanks.

**Comment by vsoftco** [comment]
Thanks, for some reason that flag ended up with NO (although the default was YES). Set back to YES now, in the devel branch which will be merged with the future release.
