### ISSUE TITLE
Bit numbering of the classical registers

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#75]
The example [qasm2.cpp](https://github.com/softwareQinc/qpp/blob/master/examples/qasm/qasm2.cpp) takes this snippet as an input:

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[2];
> qreg qqq[1];
> x q[0];
> 
> creg c[2];
> measure q -> c;
> 
> // if (c==1) x qqq[0]; // This is to prove the c is equal to one here.
> 
> creg ccc[1];
> measure qqq[0] -> ccc[0];

We will get this:

```
measured/discarded (destructive): []
non-measured/non-discarded: [0, 1, 2]
last probs: [1, 1, 1]
last dits: [1, 0, 0]
stats:
	reps: 1
	outcomes: 1
	[1 0 0]: 1
>> END ENGINE STATISTICS

>> Final state:
0   0   0   0   1   0   0   0 
```
That looks intuitive because the "last dits" can be evaluated to 4 if the 1 is the most significant bit, and the final state matches that.

But, if we look at the` if (c==1) `in the QASM code above, the classical register `c` is evaluated to 1 at that point. That seems to suggest the 1 in the "last dits" is the least significant bit.

I cannot find anything specific to bit numbering of the classical registers in the QASM spec. If the particular evaluation of classical registers is a Quantum++ implementation decision, would it be nice to have an engine function to print out the values of the classical registers in addition to the existing statistics? That would clearly indicate the presentation of the "last dits" and the classical register values are different things.

More important, I hope the bit numbering of other quantum platforms is compatible with that of the Quantum++.

Thanks.

**Comment by vsoftco** [comment]
@DevelopDaily In Quantum++ the classical registers are stored with the least significant bit first (little-endian). So indeed the `[1 0 0]` means that the least significant bit is 1 (the zero-th bit), then the 1th bit is zero and so on. There is already a member function, `QEngine::get_dits()`, that retrieves the classical dits from the last run of the engine (separately from the statistics). I've added a note in the doxygen part for `QEngine::set/get_dits`, "\note When interfacing with OpenQASM, the classical dits are stored in little-endian order, i.e. the least significant bit is stored first".

Overall I don't think there is any particular convention on what endianness to use. In Quantum++, the classical registers are supposed to be just that, and not necessarily re-interpreted as a value. But I agree, when interfacing with OpenQASM, one need to clearly specify what ordering is used. I believe I use the same ordering as OpenQASM.

Is this addressing the issue?
Thanks!

**Comment by DevelopDaily** [comment]
Fantastic! Now, I notice both `get_dits()` and `get_dit()`. It is a sheer joy to work with the Quantum++ API.

Thanks.

**Comment by vsoftco** [comment]
@DevelopDaily Thanks, glad you like it!
