### ISSUE TITLE
Bug report: rz(0)

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#77]
I run the Quantum++ example [qasm2](https://github.com/softwareQinc/qpp/blob/master/examples/qasm/qasm2.cpp) on this QASM file:

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[1];
> rz(0) q[0];

The output is like this:

```
>> BEGIN CIRCUIT
nq = 1, nc = 0, d = 2, name = ""
0 CUSTOM, target = [0], name = "rz"
step count: 1
total gate count: 1
total gate depth: 1
total measurement count: 0
total measurement depth: 0
total depth: 1
>> END CIRCUIT

>> BEGIN ENGINE STATISTICS
last probs: []
last dits: []
>> END ENGINE STATISTICS

>> Final state:
0   0 
```
The final state is not valid, is it?

**Comment by vsoftco** [comment]
@DevelopDaily Thanks, certainly not valid, will look into asap.

**Comment by DevelopDaily** [comment]
Another test case:

> OPENQASM 2.0;
> include "qelib1.inc";
> 
> qreg q[1];
> ry(pi/2) q;
> rz(pi/2) q;

The output:

```
>> BEGIN CIRCUIT
nq = 1, nc = 0, d = 2, name = ""
0 CUSTOM, target = [0], name = "ry"
1 CUSTOM, target = [0], name = "rz"
step count: 2
total gate count: 2
total gate depth: 2
total measurement count: 0
total measurement depth: 0
total depth: 2
>> END CIRCUIT

>> BEGIN ENGINE STATISTICS
last probs: []
last dits: []
>> END ENGINE STATISTICS

>> Final state:
0   0.707107i
```
The final state is not valid either.

**Comment by vsoftco** [comment]
@DevelopDaily fixed on the devel branch, does it work now?

**Comment by DevelopDaily** [comment]
Amazing!

I need Quantum++ to verify a few issues on the `staq`. Now, I've got it. Thanks!
