### ISSUE TITLE
Relationship between the bit numbering of quantum registers and the indices of the final state

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#78]
Here is a QASM file, representing the value 1.

```
OPENQASM 2.0;
include "qelib1.inc";

qreg a[3];

x a[0]; // a = 001
```
If we run it, we will get the final state:

`0 0 0 0 1 0 0 0`

The final state indicates the value 4. That suggests each follows a different endianness. I guess the latter is from a tensor product of `|a[0]> |a[1]> |a[2]>`. Well, is there anything wrong to produce the final state from a tensor product of ` |a[2]> |a[1]> |a[0]>`?  One would think the final state should be:

`0 1 0 0 0 0 0 0`

You explained the endianness of the classical registers clearly in the Issue 75. Would you please comment on this issue?

**Comment by vsoftco** [comment]
Hi,

Here the same convention is used as mentioned in Issue 75, that is |a0>|a1>|a2>. The left-most is the zero qubit. So `x a[0]` change `a[0]` from `(1 0)` to `(0 1)` (as column vectors). From which it follows that `(0 1) \otimes (1 0) \otimes (1 0)`, which is `0 0 0 0 1 0 0`. Again, qubit zero (least significant if you want to call it like that) is stored at the leftmost position (or, at the lowest address), so it follows the same little-endian convention as mentioned  in the Issue 75.

**Comment by DevelopDaily** [comment]
Thanks.
