### ISSUE TITLE
The problem in the include/qasm/preprocessor.h

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#80]
When I look at [this file](https://github.com/softwareQinc/qpp/blob/master/include/qasm/preprocessor.h), I notice you have got the extra `r` and `cswap `gates. That is cool. So, I use that as my template to make my own `qelib1.inc`, which includes more of my own custom gates.

That does not work if I do it verbatim. The trouble is on these lines:

```
    "gate cswap a,b,c { cx c,b; ccx a,b,c; cx c,b; }\n"
    "gate ch a,b { s b; h b; t b; cx a,b; tdg b; h b; sdg b; }\n"
    "gate ccx a,b,c { h c; cx b,c; tdg c; cx a,c; t c; cx b,c; tdg c; cx a,c; "
```

The `ccx `is referenced in the first line before it is defined later. Well, I can fix my `qelib1.inc` easily.

I gather you may be interested in assessing whether those lines affect other parts of the system.

**Comment by vsoftco** [comment]
@DevelopDaily good point, I think I just need to flip the order so everything is defined before usage

**Comment by vsoftco** [comment]
@DevelopDaily Fixed
