### ISSUE TITLE
Error in computing measurement probabilities

### ISSUE THREAD

**Issue by ryanhill1** [softwareQinc/qpp#90]
I constructed the following circuit in qpp:

<img width="432" alt="Screen Shot 2020-12-13 at 9 20 07 PM" src="https://user-images.githubusercontent.com/46977852/102033340-2fff3380-3d89-11eb-9d7f-0b7c511653dc.png">
The correct Z-basis measurement probabilities should be

     >> probability q0: [0.5, 0.5]
     >> probability q1: [0.75, 0.25]

However, the actual measurement probabilities were

     >> probability q0: [0.5, 0.5]
     >> probability q1: [1, 0]

The qpp code I used is here: 

    using namespace qpp;
    
    std::vector<idx> qubits{0, 0};

    ket psi = mket(qubits);
    ket result = psi;
    
    cmat U(2,2);
    U << 1, 0, 0, omega(-4); // e^-i*pi/2
    
    result = apply(result, gt.H, {0});
    result = apply(result, gt.H, {1});
    result = applyCTRL(result, U, {0}, {1});
    result = apply(result, gt.H, {1});

    auto measured0 = measure(result, gt.Z, {0});
    auto measured1 = measure(result, gt.Z, {1});
    
    std::cout << ">> probability q0: ";
    std::cout << disp(std::get<PROB>(measured0), ", ") << '\n';
    
    std::cout << ">> probability q1: ";
    std::cout << disp(std::get<PROB>(measured1), ", ") << '\n';
    
    /*
     
     EXPECTED (CORRECT) OUTPUT
     >> probability q0: [0.5, 0.5]
     >> probability q1: [0.75, 0.25]

     ACTUAL (INCORRECT) OUTPUT
     >> probability q0: [0.5, 0.5]
     >> probability q1: [1, 0]
     
     */

In both the Quirk simulation and the qpp program I use
<img width="143" alt="Screen Shot 2020-12-13 at 9 35 57 PM" src="https://user-images.githubusercontent.com/46977852/102034120-38f10480-3d8b-11eb-8565-c91f979fe750.png">
for λ = -π/2.

**Comment by vsoftco** [comment]
The problem is `omega(-4); // e^-i*pi/2`. The function `omega` assumes unsigned integers (as documented, suppose to be the D-th root of identity), so `-4` becomes max unisgned - 4. If you directly use `U << 1, 0, 0, -1_i;` then you get the correct probabilities. 

Btw, for this kind of quick circuit calculations, I suggest to use a `qpp::QCircuit` in combination with a `qpp::QEngine`.

**Comment by ryanhill1** [comment]
Brilliant, thank you!
