### ISSUE TITLE
The phase estimation example - qpe.cpp

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#96]
I think the example has a minor issue. The `qpp `convention is that the `q0 `is the most significant bit, but the example uses it as the least significant bit.

The developer may be given the freedom to interpret the endianness in his own way as long as he arranges the code subsequently to treat `q0 `as the least significant bit. But, that may confuse some users down the road, since the examples serve the purpose of documentation.

**Comment by DevelopDaily** [comment]
The example `qpe.cpp` shows how the low-level API could be used to do the job. I suggest you add another phase estimation example to showcase the power of the high-level `qpp `API. Something like this:

```
#include <iostream>
#include "qpp.h"

int main() {
    using namespace qpp;
    auto U = gt.T; //The phase of the U to be estimated.

    QCircuit qc{4, 3};
    qc.gate_fan(gt.H, {0,1,2}).gate(gt.X, 3);
    qc.CTRL(U, 2, 3).CTRL(U * U, 1, 3).CTRL(U * U * U * U, 0, 3);
    qc.TFQ({0,1, 2});
    
    QEngine engine{qc};
    engine.execute(100);
    
    auto stats = measure(engine.get_psi(), kron(gt.Z, gt.Z, gt.Z), {0, 1, 2});
    auto measured_result = std::get<RES>(stats);
    std::cout<<"Estimated phase: "<< measured_result / pow(2, 3) <<std::endl;
}
```

**Comment by vsoftco** [comment]
@DevelopDaily Nice, thanks! Was thinking of adding a QCircuit example, thanks for writing it. I'll add/modify soon.

**Comment by vsoftco** [comment]
@DevelopDaily How does this look?

```
#include <cmath>
#include <iostream>
#include <vector>

#include "qpp.h"

int main() {
    using namespace qpp;

    idx nq = 3, nc = 1; // nc stores a 'dit'
    std::cout << ">> Quantum phase estimation quantum circuit simulation on ";
    std::cout << "n = " << nq << " qubits\n\n";

    cmat U(2, 2); // initialize a unitary operator
    // use T-Gate as example; we expect estimated theta = 1/8.
    double theta = 1 / 8.;
    U << 1, 0, 0, std::exp(2 * pi * 1_i * theta);

    QCircuit qc{nq, nc};
    std::vector<idx> first_qubits(nq - 1);
    idx last_qubit = nq - 1;
    std::iota(first_qubits.begin(), first_qubits.end(), 0);

    qc.gate_fan(gt.H, first_qubits).gate(gt.X, last_qubit);
    for (idx i = last_qubit; i-- > 0;) {
        qc.CTRL(U, i, last_qubit);
        U = powm(U, 2);
    }
    qc.TFQ(first_qubits);
    qc.measureZ(first_qubits, 0);

    QEngine engine{qc};
    engine.execute();
    auto measured_result = engine.get_dit(0);
    double theta_e = measured_result / std::pow(2, first_qubits.size());

    std::cout << ">> Input theta = " << theta << '\n';
    std::cout << ">> Estimated theta = " << theta_e << '\n';
    std::cout << ">> Norm difference: " << std::abs(theta_e - theta) << '\n';
}
```

**Comment by vsoftco** [comment]
@DevelopDaily Done. See https://github.com/softwareQinc/qpp/blob/devel/examples/qpe.cpp and https://github.com/softwareQinc/qpp/blob/devel/examples/circuits/quantum_phase_estimation.cpp Both are now unified and use the same conditions.

**Comment by DevelopDaily** [comment]
Very nice! 

Just a suggestion on this:

`cmat U(2, 2); // initialize a unitary operator`

Could you please use a higher dimension unitary, say, for 2 or 3 qubits? That would be even more generic and educational. Qiskit people and most professors like to use the single qubit `T` gate as an example? If your example has a few more qubits, that would be a breath of fresh air.

**Comment by vsoftco** [comment]
@DevelopDaily Thanks, that's a good suggestion. Here it is for 2-qubit target (although can be at once extended to more) https://github.com/softwareQinc/qpp/blob/main/examples/circuits/quantum_phase_estimation.cpp

**Comment by DevelopDaily** [comment]
Perfect! Thanks.

**Comment by vsoftco** [comment]
@DevelopDaily Any remaining issues with it?

**Comment by DevelopDaily** [comment]
Just a friendly reminder. Have you forgotten something:-)? Here is the lilne:

`    double theta = 0.25;`

I just noticed you hardcoded the two `T` gates when you changed the circuit to a 2-qubit one. The theta is a dangling variable now.

I think your original code regarding the U initialization is better. I mean, you could do something like this, based on your original intent:

```
    double theta = 0.25;
    cmat U(2, 2); // initialize a unitary operator
    U << 1, 0, 0, std::exp(pi * 1_i * theta);
    U = kron(U, U);
```

**Comment by vsoftco** [comment]
Ohhh yeah, ugly... I'll get rid of that

**Comment by vsoftco** [comment]
Done, thanks for the careful code review :)

**Comment by DevelopDaily** [comment]
Perfect. Thanks!
