### ISSUE TITLE
Typos of documentation of QCircuit.CTRL()?

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#97]
Two of the signatures of the function have this:

`const std::vector< idx > & | target,`

But the textual description of the function says:

> Applies the single qudit controlled gate _U_...
> 
> **Parameters**
> 
> **U**        Single qudit quantum gate

When the target has more than one qudit in it, the U won't be a single qudit gate, will it?

**Comment by vsoftco** [comment]
I just realized `qpp::CTRL` is indeed correct as is (I though was actually buggy, long time since I wrote it). It applies `U` to every single qudit in the target. So it's like CTRL-U-U-U-...U. One needs `CTRL_custom()` to apply a multi-qudit unitary. I modified the QPE example accordingly.

**Comment by DevelopDaily** [comment]
The `CTRL_joint()` sounds much better.

Speaking of documentation, I have found the Eigen project uses a nice style: the Eigen people scatter example code widely in their API documentation. When the plain English text is inadequate, the code snippet usually settles the case nicely.

**Comment by vsoftco** [comment]
@DevelopDaily Thanks, changed to `[c]CTRL_joint()`.

**Comment by DevelopDaily** [comment]
Great. Thanks.
