### ISSUE TITLE
The implementation of rotations

### ISSUE THREAD

**Issue by DevelopDaily** [softwareQinc/qpp#99]
Here are two QASM files. I expect them to produce the same final states, but they don't. Could you please comment on them?

This file produces the correct state:

```
OPENQASM 2.0;
include "qelib1.inc";

qreg ctrl[1];
qreg q[1];

x ctrl[0];

h q[0];
rz((pi/4)+(pi/2)) q[0];

```
Its result is:

```
>> Final state:
0   0   0.707107   -0.5 + 0.5i
```

But, this file doesn't.

```
OPENQASM 2.0;
include "qelib1.inc";

qreg ctrl[1];
qreg q[1];

x ctrl[0];

ch ctrl[0], q[0];
crz((pi/4)+(pi/2)) ctrl[0], q[0];
```

Its result is:

```
>> Final state:
0   0   0.270598 - 0.653281i  0.270598 + 0.653281i
```
Well, it is almost correct -- the probabilities are correct. The phases of the state seem to be wrong.

The second file basically uses the `ctrl[0]` to control the other qubit. Since the `ctrl[0]` is 1, the two circuits should be deemed identical.

**Comment by vsoftco** [comment]
Thanks! Related to #70 , we ended up implementing RZ in the way described in #70, but didn't do this for crz. will modify and document shortly

**Comment by vsoftco** [comment]
@DevelopDaily Fixed, please let me know if there are still problems with it.

**Comment by DevelopDaily** [comment]
Hooray! Like a charm. 

Thanks.
